name: platalea.vq
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - blosc=1.19.0=hd408876_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py38_0
  - configargparse=1.2.3=py_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cython=0.29.20=py38he6710b0_0
  - decorator=4.4.2=py_0
  - freetype=2.10.2=h5ab3b9f_0
  - h5py=2.10.0=py38h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - intel-openmp=2020.1=217
  - ipython=7.16.1=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - jedi=0.17.1=py38_0
  - joblib=0.15.1=py_0
  - jpeg=9b=h024ee3a_2
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h7b6447c_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - lz4-c=1.9.2=he6710b0_0
  - lzo=2.10=h7b6447c_2
  - mkl=2020.1=217
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.1.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - mock=4.0.2=py_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.9.0=py38hfd86e86_0
  - numexpr=2.7.1=py38h423224d_0
  - numpy=1.18.5=py38ha1c710e_0
  - numpy-base=1.18.5=py38hde5b4d6_0
  - olefile=0.46=py_0
  - openssl=1.1.1g=h7b6447c_0
  - pandas=1.0.5=py38h0573a6f_0
  - parso=0.7.0=py_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=7.1.2=py38hb39fc2d_0
  - pip=20.1.1=py38_1
  - prompt-toolkit=3.0.5=py_0
  - ptyprocess=0.6.0=py38_0
  - pygments=2.6.1=py_0
  - pytables=3.6.1=py38h9fd0a39_0
  - python=3.8.3=hcff3b4d_2
  - python-dateutil=2.8.1=py_0
  - pytorch=1.5.1=py3.8_cuda10.1.243_cudnn7.6.3_0
  - pytz=2020.1=py_0
  - pyyaml=5.3.1=py38h7b6447c_1
  - readline=8.0=h7b6447c_0
  - scikit-learn=0.23.1=py38h423224d_0
  - scipy=1.5.0=py38h0b6359f_0
  - setuptools=47.3.1=py38_0
  - six=1.15.0=py_0
  - snappy=1.1.8=he6710b0_0
  - sqlite=3.32.3=h62c20be_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.6.1=py38_cu101
  - traitlets=4.3.3=py38_0
  - wcwidth=0.2.5=py_0
  - wheel=0.34.2=py38_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h0b5b093_3
  - pip:
    - editdistance==0.5.3
    - intervaltree==3.0.2
    - pydub==0.24.1
    - sortedcontainers==2.2.2
    - git+https://github.com/bootphon/h5features.git@master
    - git+https://github.com/bootphon/ABXpy.git@master
    - git+https://github.com/bootphon/tdev2.git@master
    - git+https://github.com/bootphon/zerospeech2020.git@master
    - git+https://github.com/gchrupala/ursa.git@master
    - git+https://github.com/gchrupala/lyz.git@master
prefix: /home/gchrupal/miniconda3/envs/platalea.vq

